#!/usr/bin/env python3
# Win7Taskbar - icon sources -> base64 include files
# Copyright (c) 2026 Win7Taskbar contributors - GPL v3 or later
#
# Turns the PNG sources kept in assets/icon-sources/ into the C++ include
# files that the native core embeds, so that the DLL keeps no external
# dependency on any image file.
#
# The PNG sources are NEVER committed (see .gitignore): only the generated
# .inc files are, and they are the single source of truth for the managed and
# native sides (pass --cs-out only when a managed copy is really needed).
#
# Why the strip mode cuts on the alpha bounding box: a sprite strip drawn by
# hand has no exact grid, and hand-measured offsets are the classic source of
# "one pixel of the neighbour" artefacts. Cropping each glyph to the bounding
# box of its own non-transparent pixels makes the result independent of any
# measurement, and records the real native size of every glyph in the table.
#
# Requirements:
#     pip install pillow
#
# Examples:
#     # the tray icons (volume, network, battery strip) in one file
#     python3 "compilation files/icons_to_base64.py" \
#         --icon kVolume0=assets/icon-sources/volume-0.png \
#         --icon kVolume1=assets/icon-sources/volume-1.png \
#         ... \
#         --strip assets/icon-sources/battery-strip.png \
#         --prefix kBattery --names kBattery0,kBattery1,... \
#         --cpp-out native/src/TrayIconAssets.inc
#
#     # the battery strip of the flyout (31 glyphs, Windows 7 order)
#     python3 "compilation files/icons_to_base64.py" --style battery \
#         --strip assets/icon-sources/Bitmap303.png \
#         --names kGreen1,...kPlug \
#         --cpp-out native/src/BatteryAssets.inc

from __future__ import annotations

import argparse
import base64
import io
import os
import re
import sys
import textwrap

try:
    from PIL import Image, ImageDraw
except ImportError:  # pragma: no cover - handled as a user-facing error
    print("error: Pillow is required (pip install pillow)", file=sys.stderr)
    raise SystemExit(2)

# ---------------------------------------------------------------------------
# templates
# ---------------------------------------------------------------------------

STRUCT = "struct IconB64 { const char* b64; int nativeW; int nativeH; };"

TRAY_HEADER = """\
// Win7Taskbar - tray icon assets, generated by
// "compilation files/icons_to_base64.py" from the PNG sources in
// assets/icon-sources/ (never committed: see .gitignore).
//
// DO NOT EDIT BY HAND: re-run the script after replacing a source PNG.
//
// These are the icons Win7Taskbar shows by itself when the matching system
// icon cannot be read from Explorer (see TrayFallbackIcons.cpp): they are a
// fallback, never a replacement for a bitmap that is readable.
"""

TRAY_FOOTER = """\
/* Table: index -> glyph. Idx* names are provided by the enum below so that
 * the C++ code never depends on a position. */
static const IconB64 kAll[] = {
%(entries)s};

enum Idx {
%(idx)s    IdxCount = %(count)d,
};

} // namespace trayassets
} // namespace w7t
"""

BATTERY_HEADER = """\
// Win7Taskbar - battery icons cut from the strip supplied in
// assets/icon-sources/ (never committed: see .gitignore).
// Cut measured on the alpha bounding box of every glyph: no icon is invented
// and no size is hard-coded by hand.
//
// DO NOT EDIT BY HAND: re-run
//   python3 "compilation files/icons_to_base64.py" --style battery ...
//
// Order: 0-9 green (10..100%%), 10-19 yellow (10..100%%), 20-25 red (10..60%%),
// 26 empty/grey, 27 battery with X (missing), 28 warning triangle,
// 29 circle with X (charge error), 30 plug (AC).
"""

BATTERY_FOOTER = """\
/* Table: index -> glyph. */
static const IconB64 kAll[] = {
%(entries)s};

/* Idx* prefix so that it does not clash with the base64 array names. The
 * names say what the drawing shows, because that is what the callers pick:
 * the strip has no colour variants (the fill is white), so "low" and "full"
 * differ by the height of the fill, not by a colour. */
enum Idx {
    IdxLevelBase = 0,    /* on battery: + level 1..10 -> base + lvl - 1 */
    IdxChargingBase = 10,/* on AC, battery + plug: same level arithmetic */
    IdxLowBase = 20,     /* low/critical levels 1..6 */
    IdxEmpty = 26,       /* battery outline, no fill (unknown/absent) */
    IdxNoBatt = 27,      /* on AC with no battery at all */
    IdxWarn = 28,        /* warning triangle */
    IdxChargeErr = 29,   /* AC plug + red X: charging refuses */
    IdxCount = %(count)d,
};

} // namespace battassets
} // namespace w7t
"""

# The 31 glyph names of the Windows 7 battery strip, in order.
BATTERY_NAMES = (
    ["kGreen%d" % i for i in range(1, 11)]
    + ["kYellow%d" % i for i in range(1, 11)]
    + ["kRed%d" % i for i in range(1, 7)]
    + ["kEmpty", "kNoBatt", "kWarn", "kChargeErr", "kPlug"]
)

# ---------------------------------------------------------------------------
# helpers
# ---------------------------------------------------------------------------


def log(message: str) -> None:
    print(message, flush=True)


def load_rgba(path: str) -> Image.Image:
    if not os.path.isfile(path):
        raise SystemExit("error: %s not found" % path)
    return Image.open(path).convert("RGBA")


def alpha_bbox(image: Image.Image, box=None):
    """Bounding box of the non-transparent pixels, or None when empty."""
    if box is not None:
        image = image.crop(box)
    return image.split()[3].getbbox()


def trim(image: Image.Image, box=None) -> Image.Image:
    bbox = alpha_bbox(image, box)
    if bbox is None:
        raise SystemExit("error: a glyph is fully transparent, nothing to cut")
    if box is not None:
        left, top = box[0], box[1]
        bbox = (bbox[0] + left, bbox[1] + top, bbox[2] + left, bbox[3] + top)
    return image.crop(bbox)


def strip_slices(image: Image.Image, alpha_cut: int = 0):
    """Column ranges of the glyphs of a horizontal strip.

    Glyphs are separated by transparent columns; the cut itself is then
    refined on each glyph's own alpha bounding box, so a strip with uneven
    spacing or a non-transparent background line still works as long as the
    columns between the glyphs are empty.

    ``alpha_cut`` is the alpha value below which a pixel counts as empty. The
    default (0) treats any non-zero alpha as ink, which keeps glyphs whose
    anti-aliasing bleeds one column into the neighbour together. Raising it
    (e.g. 16) separates two drawings that touch only through faint pixels,
    without any coordinate being written by hand.
    """
    alpha = image.split()[3]
    width, height = image.size
    pixels = alpha.load()
    columns = []
    for x in range(width):
        empty = True
        for y in range(height):
            if pixels[x, y] > alpha_cut:
                empty = False
                break
        columns.append(not empty)

    spans = []
    start = None
    for x, filled in enumerate(columns):
        if filled and start is None:
            start = x
        elif not filled and start is not None:
            spans.append((start, x))
            start = None
    if start is not None:
        spans.append((start, width))
    return spans


def png_base64(image: Image.Image) -> str:
    buffer = io.BytesIO()
    image.save(buffer, format="PNG", optimize=True)
    data = base64.b64encode(buffer.getvalue()).decode("ascii")
    return "\n".join(textwrap.wrap(data, 108))


def c_identifier(name: str) -> str:
    if not re.fullmatch(r"[A-Za-z_][A-Za-z0-9_]*", name or ""):
        raise SystemExit("error: '%s' is not a valid C++ identifier" % name)
    return name


# ---------------------------------------------------------------------------
# sample icons (development aid)
# ---------------------------------------------------------------------------


def make_samples(out_dir: str) -> None:
    """Draws the placeholder source PNGs used when the real artwork is missing.

    Windows 7 tray metrics: 16x16 glyphs at 100% scaling, drawn here at 32x32
    so that they stay crisp when the shell scales them. These files are a
    development standby, not the official artwork: drop the real PNGs in
    assets/icon-sources/ with the same names and re-run the script.
    """
    os.makedirs(out_dir, exist_ok=True)
    size = 32
    white = (255, 255, 255, 255)
    dark = (40, 40, 40, 255)
    green = (86, 176, 66, 255)
    yellow = (228, 187, 60, 255)
    red = (200, 60, 50, 255)

    def draw_bars(level, muted):
        image = Image.new("RGBA", (size, size), (0, 0, 0, 0))
        d = ImageDraw.Draw(image)
        for i in range(4):
            filled = (not muted) and i < level
            x0 = 6 + i * 6
            top = 22 - i * 4
            d.rectangle([x0, top, x0 + 4, 24],
                        fill=white if filled else (150, 150, 150, 255))
        if muted:
            d.line([5, 6, 26, 26], fill=red, width=3)
            for i in range(4):
                x0 = 6 + i * 6
                d.rectangle([x0, 22 - i * 4, x0 + 4, 24],
                            fill=(150, 150, 150, 255))
        return image

    def draw_battery(percent, colour):
        image = Image.new("RGBA", (size, size), (0, 0, 0, 0))
        d = ImageDraw.Draw(image)
        d.rectangle([6, 8, 27, 24], outline=white, width=2)
        d.rectangle([27, 13, 29, 19], fill=white)
        inner = int((27 - 9) * percent / 100)
        if inner > 0:
            d.rectangle([9, 11, 9 + inner, 21], fill=colour)
        return image

    def draw_network(level):
        image = Image.new("RGBA", (size, size), (0, 0, 0, 0))
        d = ImageDraw.Draw(image)
        for i in range(5):
            x0 = 4 + i * 5
            top = 24 - i * 4
            filled = i < level
            d.rectangle([x0, top, x0 + 3, 26],
                        fill=white if filled else (110, 110, 110, 255))
        return image

    def draw_warning(badge, colour):
        image = Image.new("RGBA", (size, size), (0, 0, 0, 0))
        d = ImageDraw.Draw(image)
        d.polygon([(16, 4), (29, 27), (3, 27)], fill=yellow, outline=dark)
        d.text((13, 10), badge, fill=dark)
        return image

    # volume-0 = muted, volume-1..3 = low/medium/high (Windows 7 order).
    draw_bars(0, True).save(os.path.join(out_dir, "volume-0.png"))
    for level in range(1, 4):
        draw_bars(level, False).save(os.path.join(out_dir, "volume-%d.png" % level))
    for level in range(6):
        draw_network(level).save(os.path.join(out_dir, "network-%d.png" % level))
    draw_warning("!", None).save(os.path.join(out_dir, "network-warning.png"))
    draw_warning("x", None).save(os.path.join(out_dir, "network-not-working.png"))

    # One strip with the 31 battery glyphs, Windows 7 order.
    glyphs = []
    for percent in range(10, 101, 10):
        glyphs.append(draw_battery(percent, green))
    for percent in range(10, 101, 10):
        glyphs.append(draw_battery(percent, yellow))
    for percent in range(10, 70, 10):
        glyphs.append(draw_battery(percent, red))
    empty = Image.new("RGBA", (size, size), (0, 0, 0, 0))
    ImageDraw.Draw(empty).rectangle([6, 8, 27, 24], outline=(150, 150, 150, 255), width=2)
    glyphs.append(empty)
    nobatt = draw_battery(0, red)
    ImageDraw.Draw(nobatt).line([6, 8, 27, 24], fill=red, width=3)
    glyphs.append(nobatt)
    glyphs.append(draw_warning("!", None))
    charge_error = draw_battery(30, red)
    ImageDraw.Draw(charge_error).line([6, 24, 27, 8], fill=red, width=3)
    glyphs.append(charge_error)
    plug = Image.new("RGBA", (size, size), (0, 0, 0, 0))
    d = ImageDraw.Draw(plug)
    d.rectangle([13, 4, 19, 12], fill=white)
    d.line([16, 12, 16, 22], fill=white, width=3)
    d.line([11, 26, 21, 26], fill=white, width=3)
    glyphs.append(plug)

    strip = Image.new("RGBA", (size * len(glyphs), size), (0, 0, 0, 0))
    for index, glyph in enumerate(glyphs):
        strip.paste(glyph, (index * size, 0), glyph)
    strip_path = os.path.join(out_dir, "battery-strip.png")
    strip.save(strip_path)
    log("wrote %d tray PNGs and the battery strip in %s (%s)"
        % (7 + 2, out_dir, strip_path))


# ---------------------------------------------------------------------------
# main
# ---------------------------------------------------------------------------


def parse_args(argv):
    parser = argparse.ArgumentParser(
        description="Convert the PNG icon sources into the native .inc tables.")
    parser.add_argument("--icon", action="append", default=[], metavar="NAME=FILE",
                        help="single icon; repeatable, order is preserved")
    parser.add_argument("--strip", metavar="FILE",
                        help="horizontal strip cut on the alpha bounding box")
    parser.add_argument("--alpha-cut", type=int, default=0, metavar="N",
                        help="alpha below N counts as empty when the strip is "
                             "split (default 0: any ink splits)")
    parser.add_argument("--cells", metavar="LIST",
                        help="comma-separated indices of the strip glyphs to "
                             "use, in order: for a strip whose drawing order "
                             "is not the order of the table (see --list-runs)")
    parser.add_argument("--note", action="append", default=[], metavar="TEXT",
                        help="line added to the generated header (repeatable): "
                             "use it to record how the drawings were mapped")
    parser.add_argument("--list-runs", action="store_true",
                        help="print the glyph inventory of --strip with sizes, "
                             "then exit")
    parser.add_argument("--names", metavar="LIST",
                        help="comma-separated names for the glyphs of --strip")
    parser.add_argument("--names-file", metavar="FILE",
                        help="file with one name per line, for long strips")
    parser.add_argument("--prefix", default="kIcon",
                        help="name prefix used when --names lists numbers/suffixes")
    parser.add_argument("--style", choices=("tray", "battery"), default="tray",
                        help="output template (default: tray)")
    parser.add_argument("--cpp-out", default="native/src/TrayIconAssets.inc",
                        help="C++ include file to write")
    parser.add_argument("--cs-out",
                        help="optional managed copy (TrayIconAssets.cs); the "
                             "native one is the single source of truth")
    parser.add_argument("--namespace", default="w7t",
                        help="namespace of the C++ file (default: w7t)")
    parser.add_argument("--sub-namespace", default="trayassets",
                        help="inner namespace (default: trayassets / battassets)")
    parser.add_argument("--make-samples", metavar="DIR",
                        help="draw standby sample PNGs in DIR and exit")
    return parser.parse_args(argv)


def collect_glyphs(args):
    glyphs = []
    for spec in args.icon:
        if "=" not in spec:
            raise SystemExit("error: --icon expects NAME=FILE, got '%s'" % spec)
        name, path = spec.split("=", 1)
        glyphs.append((c_identifier(name), trim(load_rgba(path)), path))
    if args.strip and args.list_runs:
        image = load_rgba(args.strip)
        spans = strip_slices(image, args.alpha_cut)
        log("%s: %d glyphs (alpha cut %d)" % (args.strip, len(spans), args.alpha_cut))
        for index, span in enumerate(spans):
            glyph = trim(image, (span[0], 0, span[1], image.size[1]))
            log("    %2d  x=%3d..%-3d  %dx%d"
                % (index, span[0], span[1] - 1, glyph.size[0], glyph.size[1]))
        raise SystemExit(0)
    if args.strip:
        image = load_rgba(args.strip)
        spans = strip_slices(image, args.alpha_cut)
        if args.cells:
            wanted = []
            for token in args.cells.split(","):
                token = token.strip()
                if not token:
                    continue
                if not token.isdigit():
                    raise SystemExit("error: --cells expects indices, got '%s'" % token)
                index = int(token)
                if index >= len(spans):
                    raise SystemExit("error: --cells asks glyph %d, the strip "
                                     "has %d" % (index, len(spans)))
                wanted.append(spans[index])
            spans = wanted
        if args.names_file:
            with open(args.names_file, "r", encoding="utf-8") as handle:
                names = [line.strip() for line in handle if line.strip()]
        elif args.names:
            names = [n.strip() for n in args.names.split(",") if n.strip()]
        else:
            names = []
        if not names:
            raise SystemExit("error: --strip needs --names or --names-file")
        if len(names) != len(spans):
            raise SystemExit(
                "error: %d names but %d glyphs found in %s"
                % (len(names), len(spans), args.strip))
        for name, span in zip(names, spans):
            glyph = trim(image, (span[0], 0, span[1], image.size[1]))
            glyphs.append((c_identifier(name), glyph, args.strip))
    return glyphs


def render_cpp(args, glyphs):
    lines = []
    if args.note:
        # Documented mapping: it lives in the file it describes, next to the
        # table, so a future replacement of the source PNG does not have to
        # guess which drawing went where.
        lines.append("/*")
        for note in args.note:
            lines.append(" * " + note)
        lines.append(" */")
        lines.append("")
    for name, image, source in glyphs:
        width, height = image.size
        lines.append("/* %s (%dx%d) <- %s */" % (name, width, height, source))
        lines.append("static const char %s[] = R\"W7B(" % name)
        lines.append(png_base64(image))
        lines.append(")W7B\";")
        lines.append("")
    entries = "".join("    { %s, %d, %d },\n" % (name, image.size[0], image.size[1])
                      for name, image, _ in glyphs)

    if args.style == "battery":
        header = BATTERY_HEADER
        footer = BATTERY_FOOTER % {"entries": entries, "count": len(glyphs)}
        sub = args.sub_namespace if args.sub_namespace != "trayassets" else "battassets"
    else:
        header = TRAY_HEADER
        index_lines = "".join("    Idx%s = %d,\n" % (name[1:] if name.startswith("k") else name, i)
                              for i, (name, _, _) in enumerate(glyphs))
        footer = TRAY_FOOTER % {"entries": entries, "idx": index_lines,
                                "count": len(glyphs)}
        sub = args.sub_namespace

    body = "%s\n#pragma once\n\nnamespace %s {\nnamespace %s {\n\n%s\n\n%s\n%s" % (
        header, args.namespace, sub, STRUCT, "\n".join(lines), footer)
    return body


def render_cs(args, glyphs):
    out = ["// Win7Taskbar - generated companion of the native include "
           "(see \"compilation files/icons_to_base64.py\").",
           "// The native table stays the single source of truth: this copy only "
           "exists for code that runs without the DLL.",
           "",
           "internal static class TrayIconAssets",
           "{",
           "    internal readonly record struct Icon(byte[] Png, int Width, int Height);",
           ""]
    for name, image, _ in glyphs:
        out.append("    internal static readonly Icon %s = new Icon(_%s, %d, %d);"
                   % (name, name, image.size[0], image.size[1]))
    out.append("")
    for name, image, _ in glyphs:
        data = png_base64(image).replace("\n", "")
        out.append("    private const string _%s = \"%s\";" % (name, data))
    out.append("}")
    out.append("")
    return "\n".join(out)


def main(argv=None):
    args = parse_args(argv if argv is not None else sys.argv[1:])

    if args.make_samples:
        make_samples(args.make_samples)
        return 0

    glyphs = collect_glyphs(args)
    if not glyphs:
        raise SystemExit("error: nothing to do: pass --icon and/or --strip")

    if args.style == "battery" and not args.cells and len(glyphs) != len(BATTERY_NAMES):
        raise SystemExit("error: the battery strip has %d glyphs, expected %d "
                         "(use --cells to pick the drawings in table order)"
                         % (len(glyphs), len(BATTERY_NAMES)))

    output = render_cpp(args, glyphs)
    directory = os.path.dirname(args.cpp_out)
    if directory:
        os.makedirs(directory, exist_ok=True)
    with open(args.cpp_out, "w", encoding="utf-8", newline="\n") as handle:
        handle.write(output)
    log("wrote %s (%d glyphs)" % (args.cpp_out, len(glyphs)))
    for name, image, _ in glyphs:
        log("    %-16s %dx%d" % (name, image.size[0], image.size[1]))

    if args.cs_out:
        cs_directory = os.path.dirname(args.cs_out)
        if cs_directory:
            os.makedirs(cs_directory, exist_ok=True)
        with open(args.cs_out, "w", encoding="utf-8", newline="\n") as handle:
            handle.write(render_cs(args, glyphs))
        log("wrote %s" % args.cs_out)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
